######################################

# This script defines the project pipeline - it specifys the execution orders for all the code in this
# repo using a series of actions.

######################################

version: '3.0'

expectations:
  population_size: 100000

actions:

  # Extract data ----
  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-dir=output/data
    outputs:
      highly_sensitive:
        cohort: output/data/input.csv
        
  # Process data ----
  data_process:
    run: r:latest analysis/data_process.R
    needs: [generate_study_population]
    outputs:
      highly_sensitive:
        data: output/data/data_all.rds
  
  # Data properties      
  data_properties:
    run: r:latest analysis/data_properties.R output/data/data_all.rds output/data_properties
    needs: [data_process]
    outputs:
      moderately_sensitive:
        cohort: output/data_properties/data_all*.txt
        
  # Table 1 ----
  table_1:
    run: r:latest analysis/table_1.R
    needs: [data_process]
    outputs:
      moderately_sensitive:
        table: output/tables/table1*.html
  
  # Table 2 ----
  table_2:
    run: r:latest analysis/table_2.R
    needs: [data_process]
    outputs:
      moderately_sensitive:
        table: output/tables/table2.html
        
        
        